### ISSUE TITLE
Predicted values back to Prometheus ?

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#106]
Hi @all,

from the diagram that shows how prometheus-anomaly-detector works in combination with other tools it looks like predicted values can be fed back to Prometheus and visualized with Grafana. 

Is there already a working way to get the metrics back to Prometheus? If yes - how can it be done ?

Bye, Dirk

**Comment by 4n4nd** [comment]
Yeah, when you run the app.py, it starts a web server. You can just go to your_ip:8080/metrics to see the predicted metric values.

**Comment by DirkFries** [comment]
Well you couldn't make it easier but still I was looking for some configuration option to get a text file or something like that.
Tested and works like a charm!

Thanks a lot !
