### ISSUE TITLE
Store trained models on disk?

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#107]
Hi @all,

as far as I know trained models are not stored on disk after if the software is shut down. So after a restart all models have to be trained again. Depending on timerange und number of metrics this can take hours.

Maybe it would be a nice additional feature to add the possibility if saving trained models.

Bye, Dirk

**Comment by 4n4nd** [comment]
it doesn't really make sense for a model like prophet as once the model has been trained, it cannot be retrained. So you essentially have to train it again from scratch.

**Comment by DirkFries** [comment]
Ok, I think you are right :-)
Thanks a lot!
