### ISSUE TITLE
Make use of cores?

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#108]
Hi @all,

while training the model PAD seems to make use of only one core.
I think it would be a nice feature if PAD could use more cores by making use of multithreading or mutiple processes to speed things up.

Bye Dirk

**Comment by 4n4nd** [comment]
Right now the app uses 2 processes, 1 to train the model and 1 for the tornado web server that exposes the predicted metrics. The resources that the model uses for training are fixed by prophet. 
Please correct me if I am wrong, but Prophet is not multi-processed

**Comment by DirkFries** [comment]
Hi Anand,

maybe I should point out what use case I have in mind.

Let's say you got a metric called vsphere_cpu_usage_maximum and you have 1200 Virtualmachines with this metric, each identified by a uniq name tag (e.g. name="vm1", name="vm1", name="vm3").
If you start PAD with FLT_METRICS_LIST="vsphere_cpu_usage_maximum" it will start to train the model sequential for vm1, then vm2, vm3 etc. using 1 core.
This might take up to 20 hours and you don't have the chance to do a retraining in usable intervalls.

On the other hand you can start different PAD Instances where the webserver listens on different ports with

FLT_METRICS_LIST="vsphere_cpu_usage_maximum{name='vm1'}"
FLT_METRICS_LIST="vsphere_cpu_usage_maximum{name='vm2'}"
FLT_METRICS_LIST="vsphere_cpu_usage_maximum{name='vm3'}"
FLT_METRICS_LIST="vsphere_cpu_usage_maximum{name='vm4'}"

In this case you can make use of mutiple cores (e.g. 4), but there is a lot of Managemtoverhead and waste of tcp ports und probabaly memory.

My idea was that you can configure PMA with FLT_METRICS_LIST="vsphere_cpu_usage_maximum" and PMA either recognizes the number of cores there are or it can be configured how many cores it should use and that it starts a single fbprophet process for every tag like vm1, vm2 etc.  pp
I think this would make PMA much more efficient and a lot faster.

Of course it may be, that I got something wrong because I'm still an (excited) newbie with PAD. So I wonder how you would approach to use PAD with a metric with 1200 tags ?
Do you have some hints or strategies?

Unfortunally I am not an Software Developer and so I have no idea if this is possible or not.
I just think that your software is a great addition to the Prometheus Ecosystem and so I'd like to share my ideas/thoughts about it to help to make it even better.

So, please don't take my questions/suggestions  amiss.

Bye, Dirk

**Comment by 4n4nd** [comment]
Oh yes, that seems like a very good idea. We never thought of that since we almost always use it in a container (Kubernetes/Openshift) environment with a single core of CPU assigned to it.
 
Also, the idea behind PAD was that you should be able to replace the model.py with your own model. Now, if your model is multithreaded/multiprocessed, it would not make sense to spawn multiple training processes in the PAD itself.

**Comment by DirkFries** [comment]
Hi Anand,

thanks a lot! I will try to do a work around with some wrapper script.
model.py sounds like an interesting file to look at is the near future.

Bye Dirk
