### ISSUE TITLE
Not able see predication metrics on prometheus Graph.

### ISSUE THREAD

**Issue by nandhyala** [AICoE/prometheus-anomaly-detector#110]
I have followed below document i setup prophet on EC2 machine  and pulling metrics(FLT_METRICS_LIST)  from prometheus end point(FLT_PROM_URL) and some how i dont see any result on predication metrics reports with prophet predication.

I see below continues below  o/p on prophet machine. Can you please some one help on this ?

  "Convergence detected: relative gradient magnitude is below tolerance
2020-02-27 05:05:29,945:INFO:__main__: Total Training time taken = 0:00:13.435543, for metric: container_cpu:container_cpu_usage_seconds_total:rate:sum {}
2020-02-27 05:07:30,086:INFO:schedule: Running job Every 2 minutes do train_model(initial_run=False, data_queue=<multiprocessing.queues.Queue object at 0x7fed042683d0>) (last run: 2020-02-27 05:05:29, next run: 2020-02-27 05:07:29)
2020-02-27 05:07:30,158:INFO:model: training data range: 2020-02-16 18:36:32.441999912 - 2020-02-27 05:06:32.441999912
Initial log joint probability = -624.556
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      99       14102.9     0.0341506       242.469           1           1      116
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     199       14111.8    0.00151911       266.794           1           1      244
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     299       14116.3    0.00037893       126.022      0.6299      0.6299      358
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     399       14118.4   0.000192582       86.9727      0.3648           1      479
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     499       14122.9    0.00185006       157.717           1           1      593
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     587       14124.5   0.000250693       238.923   2.704e-06       0.001      742  LS failed, Hessian reset
     599       14124.6   6.07051e-05       83.8182      0.7625      0.7625      755
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     645       14124.6   5.48574e-07       86.1275      0.3767           1      812
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
2020-02-27 05:07:39,472:INFO:__main__: Total Training time taken = 0:00:09.362668, for metric: container_cpu:container_cpu_usage_seconds_total:rate:sum {}"

**Comment by 4n4nd** [comment]
In your Prometheus targets list, can you check if it was successfully able to scrape the anomaly-detector?

**Comment by nandhyala** [comment]
@4n4nd Thanks Anand Sanmukhani ,In Prometheus targets list dash board i dont see any anomaly-detector entire .

python3 app.py script i see  yhat  yhat_lower  yhat_upper values but same thing i am not seeing Prometheus.Please help on this issue.

" 2020-02-27 17:55:53,751:DEBUG:prometheus_api_client.prometheus_connect: start_time: 2020-02-27 17:53:53.754119
2020-02-27 17:55:53,751:DEBUG:prometheus_api_client.prometheus_connect: end_time: 2020-02-27 17:55:53.751601
2020-02-27 17:55:53,751:DEBUG:prometheus_api_client.prometheus_connect: chunk_size: None
2020-02-27 17:55:53,751:DEBUG:prometheus_api_client.prometheus_connect: Prometheus Query: container_cpu:container_cpu_usage_seconds_total:rate:sum
2020-02-27 17:55:53,753:DEBUG:urllib3.connectionpool: Starting new HTTP connection (1): ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80
2020-02-27 17:55:53,779:DEBUG:urllib3.connectionpool: http://ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80 "GET /api/v1/query?query=container_cpu%3Acontainer_cpu_usage_seconds_total%3Arate%3Asum%5B120s%5D&time=1582826154 HTTP/1.1" 200 197
2020-02-27 17:55:53,828:INFO:model: training data range: 2020-02-25 17:56:32.441999912 - 2020-02-27 17:55:32.441999912
2020-02-27 17:55:53,828:DEBUG:model: begin training
Initial log joint probability = -159.531
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      99       2672.44    0.00662214       113.375           1           1      125
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     172       2680.56    0.00135966       109.968   1.218e-05       0.001      242  LS failed, Hessian reset
     199       2680.92    0.00272163       111.415           1           1      272
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     208       2681.75    0.00213477       402.471   1.513e-05       0.001      359  LS failed, Hessian reset
     278       2683.21   0.000620649       158.737   4.925e-06       0.001      483  LS failed, Hessian reset
     299       2683.33   2.07698e-05       97.2539      0.5944      0.5944      509
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
     329       2683.34   5.97714e-08       98.7893      0.6591      0.6591      549
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
2020-02-27 17:55:56,653:DEBUG:model:                                     yhat  yhat_lower  yhat_upper
timestamp
2020-02-27 17:56:32.441999912  11.045056   -4.791490   27.309229
2020-02-27 17:57:32.441999912  11.037078   -4.108421   26.203213 "

**Comment by 4n4nd** [comment]
Can you please visit the metrics page in your browser?
i.e. `http://prom_anomaly_detector_address:8080/metrics` and check if you can see the predicted metrics. 
If you can see the predicted metrics there, can you check if your prometheus instance is configured to scrape the anomaly detector properly? 
You might need to add the anomaly detector's address in the the prometheus config some helpful docs are available [here](https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-the-sample-targets).

If none of this works, could you please show me your prometheus configuration?

**Comment by nandhyala** [comment]
Thanks @4n4nd  helping me on this issue.

1)http://172.xx.x.xx:8080/metrics -->I dont see any predicted metrics on page.
2) Can you please help me how can i add anomaly detector's address in the the prometheus config .Sorry ,I am not able make using attached document https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-the-sample-targets.
3)We are running prometheus on EKS kubernetes cluster.below is prometheus configuration from prometheus dashboard.

***************
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - role: pod
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
    scheme: http
    timeout: 10s
    api_version: v1
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: monitoring
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      separator: ;
      regex: alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      separator: ;
      regex: null
      replacement: $1
      action: drop
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: kubernetes-apiservers
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: endpoints
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
- job_name: kubernetes-nodes
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: node
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/$1/proxy/metrics
    action: replace
- job_name: kubernetes-nodes-cadvisor
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: node
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    action: replace
- job_name: kubernetes-service-endpoints
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    separator: ;
    regex: (https?)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_node
    replacement: $1
    action: replace
- job_name: prometheus-pushgateway
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    separator: ;
    regex: pushgateway
    replacement: $1
    action: keep
- job_name: kubernetes-services
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
- job_name: kubernetes-pods
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace

**Comment by 4n4nd** [comment]
We recently added new annotations to the `Service` object ([here](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/openshift/oc-deployment-template.yaml#L123-L125)), Can you please try using the updated template for the Anomaly detector service? 

This might not work if Prometheus has been deployed in a different namespace than the prometheus anomaly detector. If that's the case you might need to add another job in your Prometheus config, something like:
```yaml
- job_name: prometheus-anomaly-detector
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
        - targets: ['route_to_anomaly_detector']
          labels:
            group: 'anomaly-detection'
```

**Comment by 4n4nd** [comment]
> 1)http://172.xx.x.xx:8080/metrics -->I dont see any predicted metrics on page.

Can you check if you have the prometheus-anomaly-detector service exposed?
If not, you can do it by using `kubectl expose anomaly_detector_service_name -n namespace_where_deployed`

**Comment by nandhyala** [comment]
@4n4nd ,Sorry to ask you ,here what target value - targets: ['route_to_anomaly_detector'] host we need to update on Prometheus configuration on kubernetes  ?

**Comment by 4n4nd** [comment]
Is the Prometheus hosted in the same namespace as the anomaly detector?

**Comment by nandhyala** [comment]
@4n4nd ,

Just i want explain how i am doing here to come up both are in same page.

1)My prometheus/grafana are running on Kubernetes cluster and collecting application metrics .
2)For prometheus application created ALB end point on cluster.
3)On AWS EC2 machine have installed prophet required rpm's.
4) Downloaded repo https://github.com/AICoE/prometheus-anomaly-detector.git on EC2 machine.
5) exported below env and executed python app.py script on EC2 machine.
6) Issue is i am not understading how caan i see predication graphs on prometheus  dashboard for python app.py result.

export FLT_PROM_URL=http://axxxxxxxx.elb.eu-west-1.amazonaws.com
export FLT_RETRAINING_INTERVAL_MINUTES=5
export FLT_ROLLING_TRAINING_WINDOW_SIZE=1d
export FLT_METRICS_LIST="container_cpu:container_cpu_usage_seconds_total:rate:sum"
Can you please review above steps and correct me if i am doing wrong here.

**Comment by 4n4nd** [comment]
This application starts a web server and exposes metrics on port 8080.
After step 5, I think you need to create an ALB endpoint for the anomaly detection application, just like prometheus. Then you might get a url similar to http://axxxxxxxx.elb.eu-west-1.amazonaws.com which you can use in the prometheus config.
Sorry I don't have much experience with AWS EC2. If you can, use the deployment configurations in the openshift repo, to deploy the anomaly detector in your kubernetes cluster.

**Comment by nandhyala** [comment]
@4n4nd ,That means i need to create load balancer on EC2 machine app.py script is running ?

**Comment by 4n4nd** [comment]
Yes, because prometheus needs some kind of address that it can use to reach the anomaly detector.

**Comment by nandhyala** [comment]
got it @4n4nd ,I will create ALB on ec2 machine .

**Comment by 4n4nd** [comment]
you can test if the app is working by curling its ip inside the EC2 instance.

`curl localhost:8080/metrics` from inside the EC2 instance

**Comment by nandhyala** [comment]
[root@ip-xxxx~]# curl localhost:8080
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 20471.0
python_gc_objects_collected_total{generation="1"} 16370.0
python_gc_objects_collected_total{generation="2"} 896.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 536.0
python_gc_collections_total{generation="1"} 60.0
python_gc_collections_total{generation="2"} 4.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="4",version="3.7.4"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 9.04101888e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.05651712e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.58284575441e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.35
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 14.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
# HELP container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet Forecasted value from Prophet model
# TYPE container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet gauge
container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet{value_type="yhat"} -11.264086645780477
container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet{value_type="yhat_lower"} -19.96119988783143
container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet{value_type="yhat_upper"} -2.6234446516765177
container_cpu:container_cpu_usage_seconds_total:rate:sum_prophet{value_type="anomaly"} 1.0
[root@ip-xxxx ~]#

**Comment by 4n4nd** [comment]
exactly, these are your predicted values.
But the prometheus needs to be able to access this page from the outside.

**Comment by nandhyala** [comment]
one more question on prediction values ,I see only yhat & yhat_lower & yhat_upper but i dont see predicted metrics value ...In repo exmaple graph i see predicted metrics value line.

**Comment by 4n4nd** [comment]
`yhat` is the predicted value.
`yhat_upper` is the upper bound
`yhat_lower` is the lower bound

**Comment by nandhyala** [comment]
Really Thank you very much @4n4nd  helping me on step .I will create alb & will place new alb in Prometheus config file and will test.If still i face any issues i will update here.

**Comment by 4n4nd** [comment]
Once you create the endpoint, check it with curl if it is accessible

**Comment by nandhyala** [comment]
Sure @4n4nd

**Comment by nandhyala** [comment]
I think i no ALB I am able to get anomaly detector metrics  using ec2 http://host-ip:8080 from my prometues pods servers.Just I will place http://host-ip:8080 on prometheus config and test.

**Comment by 4n4nd** [comment]
good idea :+1:

**Comment by nandhyala** [comment]
@4n4nd ,Now i am able to see prophet yhat & yhat_lower & yhar_upper metrics on prometues dash board. But i dont have enough data to do training ...Once i have data by next week on cluster application i will run and see prediction .

Thanks you once again for your help on here ...May be i will reach out you if i need any help on prediction with my data :)

**Comment by 4n4nd** [comment]
No problem 👍
Do you want to close this issue then?

**Comment by nandhyala** [comment]
yes @4n4nd we can close this issue

**Comment by Carmezim** [comment]
I've got the anomaly detector running on K8s in the same namespace as the prometheus instance and am able to get a successful response calling `wget localhost:8000/metrics` from within the anomaly detector, but the prometheus instance cannot read from it getting `connection refused`.
```
# anomaly detector instance

--2020-12-21 03:57:27--  http://localhost:8080/metrics
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1895 (1.9K) [text]
metrics: Is a directory
```

The anomaly detector is on:
```
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: ********
  type: ClusterIP
```
Wondering if there might be anything else I'm missing. Thank you.

**Comment by 4n4nd** [comment]
@Carmezim i think this might be an issue in the way PAD is deployed in your k8s env.
Can you post your deployment manifest? I think for some reason the port 8080 for your pod is not being forwarded.

**Comment by Carmezim** [comment]
@4n4nd Hey - sorry for the delay on that. I was away.
Thank you again for getting back to me and yeah, you're probably right, here's how it's set:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus-anomaly-detector
  namespace: ***
  selfLink: >-
    /apis/extensions/v1beta1/namespaces/***/deployments/prometheus-anomaly-detector
  uid: 6c8d47a7-934b-411d-a3d0-a812b216e0b4
  resourceVersion: '431333516'
  generation: 109
  labels:
    run: prometheus-anomaly-detector
  annotations:
    deployment.kubernetes.io/revision: '49'
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-anomaly-detector
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus-anomaly-detector
    spec:
      containers:
        - name: prometheus-anomaly-detector
          image: >-
            blabla/prometheus-anomaly-detector:123
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: FLT_PROM_URL
              value: 'https://prometheus.***.com/'
            - name: FLT_PROM_ACCESS_BASIC_AUTH (I made some auth changes to use basic auth)
              value: ****
            - name: FLT_RETRAINING_INTERVAL_MINUTES
              value: 15m
            - name: FLT_METRICS_LIST
              value: sh_probe_temp
            - name: APP_FILE
              value: app.py
            - name: FLT_DATA_START_TIME
              value: 30d
            - name: FLT_ROLLING_TRAINING_WINDOW_SIZE
              value: 1d
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 109
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "prometheus-anomaly-detector-5c464f4" has successfully
        progressed.
    - type: Available
      status: 'False'
```
