### ISSUE TITLE
Would people be interested in Kubernetes deployment templates?

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-anomaly-detector#111]
Currently we only have deployment templates for openshift, should we also add native kubernetes templates so its easier for users to deploy PAD in kubernetes environments?

i.e. Deployment instead of DeploymentConfig, Ingress instead of Route

I think this way more people will be able to use it.
@hemajv @durandom @goern suggestions?

**Comment by DJMatus23** [comment]
I'm planning to spend some time trying to run this in Kubernetes.  I'm planning on just using kustomize, but I'd be happy to help get a helm chart together for it, assuming I can get it working. 🤞

**Comment by Carmezim** [comment]
People would be interested :)

**Comment by 4n4nd** [comment]
Until there is a proper deployment template the container image: `quay.io/aicoe/prometheus-anomaly-detector` can be used.
