### ISSUE TITLE
yhat & yhat_lower & yhat_upper prediction values is not accurate with current original values.

### ISSUE THREAD

**Issue by nandhyala** [AICoE/prometheus-anomaly-detector#112]
@4n4nd ,

I am plaining to use yhat value todo Kuberentes pod autoscaling (at peak time it will scale up 1000 + pods) using Prometheus original metrics (container_cpu:container_cpu_usage_seconds_total:rate) as  prediction yhat values in HPA.

I have passed below variables on prophet application node and started app.py.

export FLT_PROM_URL=http://xxxxxxx.amazonaws.com
export FLT_RETRAINING_INTERVAL_MINUTES=1
export FLT_ROLLING_TRAINING_WINDOW_SIZE=3d
export FLT_METRICS_LIST="container_cpu:container_cpu_usage_seconds_total:rate:sum"

container_cpu:container_cpu_usage_seconds_total:rate:sum = sum (rate (container_cpu_usage_seconds_total{container_name="smart-savant-cpu"}[5m]))

Below issue i have noticed on above steps:

1)I am able to see yhat & yhat_lower & yhat_upper prediction values on prometheus but some how i am not seeing correct prediction values for yhat & yhat_lower & yhat_upper on prometheus/grafanan compare to original "container_cpu:container_cpu_usage_seconds_total:rate:sum" metrics .

I have attached grafana dashboaard screen shot here.
Green bar is :container_cpu:container_cpu_usage_seconds_total:rate:sum
Sky blue bar is : yhat 
Red Bar is : yhat_upper
Orange Bar is :yhat_lower
Bottom Bar is : Anomaly detector.

Can you please help what i am doing wrong on above ,Can you please review and let me know how can i fix ?

2) How can i see furture forecast data on prometheus/grafana dashboard ?

3)How can use daily & weekly & Holiday data setting if is required & what is default prediction is doing on app.py ?

Can you please help me on above things to setup Kuberntess HPAA autoscaling on infrastructure ?

Thanks 🙏

**Comment by nandhyala** [comment]
![Screen Shot 2020-03-01 at 10 06 30 AM](https://user-images.githubusercontent.com/36256194/75631367-249a9d00-5ba7-11ea-9735-63f461253e6f.png)

**Comment by 4n4nd** [comment]
> 1)I am able to see yhat & yhat_lower & yhat_upper prediction values on prometheus but some how i am not seeing correct prediction values for yhat & yhat_lower & yhat_upper on prometheus/grafanan compare to original "container_cpu:container_cpu_usage_seconds_total:rate:sum" metrics .
I have attached grafana dashboaard screen shot here.
Green bar is :container_cpu:container_cpu_usage_seconds_total:rate:sum
Sky blue bar is : yhat
Red Bar is : yhat_upper
Orange Bar is :yhat_lower
Bottom Bar is : Anomaly detector.
Can you please help what i am doing wrong on above ,Can you please review and let me know how can i fix ?

Hey I don't really get what isn't working. To me it looks like everything is working as intended.

> 2. How can i see furture forecast data on prometheus/grafana dashboard ?

Currently we don't have any way to do this. 


> 3)How can use daily & weekly & Holiday data setting if is required & what is default prediction is doing on app.py ?

You can configure the model in the [model.py](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/model.py#L35) file.

**Comment by nandhyala** [comment]
@4n4nd ,

I dont see any issue with setup i see the yhat & yhat_lower & yhat_upper prediction values on prometheus but some how i see lot of difference between original values and  yhat & yhat_lower & yhat_upper .

![Screen Shot 2020-03-02 at 9 41 52 AM](https://user-images.githubusercontent.com/36256194/75702416-50328b80-5c6a-11ea-84fe-17004c1eb814.png)

See attached screen shot in below:
**Green bar is :** original container_cpu:container_cpu_usage_seconds_total:rate:sum
**Sky blue bar is :** yhat
**Red Bar is :** yhat_upper
**Orange Bar is** :yhat_lower
**Bottom Bar is** : Anomaly detector.

**Comment by 4n4nd** [comment]
> ![Screen Shot 2020-03-01 at 10 06 30 AM](https://user-images.githubusercontent.com/36256194/75631367-249a9d00-5ba7-11ea-9735-63f461253e6f.png)

That seems to be doing well

Or you can try giving the model more data,
`export FLT_ROLLING_TRAINING_WINDOW_SIZE=30d`

and I don't think you need to retrain your model every minute,
`export FLT_RETRAINING_INTERVAL_MINUTES=15`

This will look at the past 30 days of data and retrain the model every 15 minutes.

Hope this is helpful, otherwise you can try tweaking the model.py which is from https://facebook.github.io/prophet/

**Comment by nandhyala** [comment]
Sure @4n4nd I will try with below values ..Just i want let you know we have only last 4 days data in prometheus and see below screen shot i see lot of differences between original values & yhat's. 

![Screen Shot 2020-03-02 at 9 41 52 AM](https://user-images.githubusercontent.com/36256194/75717264-a4973480-5c85-11ea-9147-4f3ad75ae6f9.png)

Green bar is : original container_cpu:container_cpu_usage_seconds_total:rate:sum
Sky blue bar is : yhat
Red Bar is : yhat_upper
Orange Bar is :yhat_lower
Bottom Bar is : Anomaly detector.

**Comment by 4n4nd** [comment]
let the anomaly detector collect a few days of data and then see if the predictions improve

**Comment by 4n4nd** [comment]
> Just i want let you know we have only last 4 days

It should keep accumulating the data until it has 30 days of data.

**Comment by hemajv** [comment]
@nandhyala By default, the model being trained is the Prophet model. You can also try training the Fourier model by importing the `model_fourier.py` in your `app.py`  and compare between the two. As @4n4nd mentioned, due to the small amount of training data you have, it might be affecting the model's performance.

**Comment by nandhyala** [comment]
@4n4nd  @hemajv  , Really appreciate your help ! Now i am running app.py script from 4days and in progress and dont see much yhat & yhat_upper & yhat_lower values with original values.

Can you please confirm we cant predict or  training data with 1 week of data using prophet ?
![Screen Shot 2020-03-04 at 9 00 34 PM](https://user-images.githubusercontent.com/36256194/75949514-563b8e80-5e5b-11ea-9a9c-3f1a2f5a9933.png)

**Comment by hemajv** [comment]
@nandhyala I can see that few anomalies were detected. Since the `anomaly` is a 0 or 1 value, try increasing the scale for the 'anomaly' line (i.e. the orange line) on the graph so that you can visualize it better. You can predict on training data of 1 week, but the performance of the model may be better with more training data.

For training the Fourier model, change https://github.com/AICoE/prometheus-anomaly-detector/blob/master/app.py#L13 to: `import model_fourier as model`

**Comment by nandhyala** [comment]
Thanks @hemajv  ,I will check with 2 weeks data and come back if i see same issues.

Parallel i will check model_fourier as per above link and let you know.

**Comment by nandhyala** [comment]
@hemajv ,

Any idea why it is failing ata line 37 with below error after adding import model_fourier as model.

[root@ip-xxxxx prometheus-anomaly-detector]# python3 app.py
2020-03-09 18:59:45,080:INFO:configuration: Metric data rolling training window size: 1 day, 23:59:59.950370
2020-03-09 18:59:45,080:INFO:configuration: Model retraining interval: 2 minutes
2020-03-09 18:59:45,084:DEBUG:urllib3.connectionpool: Starting new HTTP connection (1): ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80
2020-03-09 18:59:45,111:DEBUG:urllib3.connectionpool: http://ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80 "GET /api/v1/query?query=container_cpu_usage_seconds_total%3Aeks_savant_cpu%3Anodegroup%3A5m_rate HTTP/1.1" 200 184
2020-03-09 18:59:45,121:DEBUG:urllib3.connectionpool: Starting new HTTP connection (1): ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80
2020-03-09 18:59:45,124:DEBUG:urllib3.connectionpool: http://ace5a9030446111eaa51406535e498bf-a39d9303f84e17f8.elb.eu-west-1.amazonaws.com:80 "GET /api/v1/query?query=container_cpu_usage_seconds_total%3Aeks_savant_cpu%3Anodegroup%3A5m_rate HTTP/1.1" 200 184
Traceback (most recent call last):
  File "app.py", line 37, in <module>
    model.MetricPredictor(
AttributeError: module 'model' has no attribute 'MetricPredictor'
[root@ip-xxxxxx prometheus-anomaly-detector]#

**Comment by nandhyala** [comment]
@hemajv ,

I have tried with model_fourier with 2 days data but i dont see much improvement . Below original  &  fouier metrics graph in grafana.

![Screen Shot 2020-03-10 at 2 00 32 PM](https://user-images.githubusercontent.com/36256194/76359068-c2911480-62d7-11ea-9b33-1682e6e4f8b3.png)

**Comment by hemajv** [comment]
@nandhyala So this is one of the drawback with Fourier, it is more of a statistical extrapolation of the values vs the Prophet model which takes into account seasonality or trend in your data. One model may perform better than the other depending on the nature of the time series metric. I would still recommend collecting at least > 2 weeks of data and re-training the Prophet/Fourier models.

**Comment by nandhyala** [comment]
Thanks @hemajv ,I will check same Prophet/Fourier models. once i get 2 weeks data.

**Comment by saswat0** [comment]
@4n4nd
This is my current metric: `sum(rate(container_cpu_usage_seconds_total{container="filebeat"}[5m]))`
Upon running this query in prometheus, I get:
<div class="form-row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -5px; margin-left: -5px; color: rgb(33, 37, 41); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-lg-12" style="box-sizing: border-box; position: relative; width: 1420px; min-height: 1px; padding-right: 5px; padding-left: 5px; flex: 0 0 100%; max-width: 100%;"><div class="list-group" role="tabpanel" style="box-sizing: border-box; display: flex; flex-direction: column; padding-left: 0px; margin-bottom: 0px;"><div class="tab-content" style="box-sizing: border-box;"><div role="tabpanel" class="tab-pane console active show" id="console0" style="box-sizing: border-box; border-left: 1px solid rgb(221, 221, 221); border-right: 1px solid rgb(221, 221, 221); border-bottom: 1px solid rgb(221, 221, 221); padding: 5px; display: block;">

Element | Value
-- | --
{} | 109.75193639945056

</div></div></div></div></div><div class="form-row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -5px; margin-left: -5px; color: rgb(33, 37, 41); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

This causes an error in prometheus-api-client: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-29-90fc056ed26d> in <module>
      2     print(unique_metric)
      3     PREDICTOR_MODEL_LIST.append(
----> 4         model.MetricPredictor(
      5             unique_metric,
      6             rolling_data_window_size=Configuration.rolling_training_window_size,

~/x_prometheus-anomaly-detector/model.py in __init__(self, metric, rolling_data_window_size)
     21     def __init__(self, metric, rolling_data_window_size="10d"):
     22         """Initialize the Metric object."""
---> 23         self.metric = Metric(metric, rolling_data_window_size)
     24 
     25     def train(self, metric_data=None, prediction_duration=15):

~/opt/anaconda3/envs/prophet-env/lib/python3.8/site-packages/prometheus_api_client/metric.py in __init__(self, metric, oldest_data_datetime)
     61             self.oldest_data_datetime = oldest_data_datetime
     62         else:
---> 63             self.metric_name = metric["metric"]["__name__"]
     64             self.label_config = deepcopy(metric["metric"])
     65             self.oldest_data_datetime = oldest_data_datetime

KeyError: '__name__'

```

There is provision for aggregation on rate in prometheus and @nandhyala has been able to run a similar [query](https://github.com/AICoE/prometheus-anomaly-detector/issues/112#issue-573591700) without errors. Any pointers on what I am doing wrong here would be very helpful
