### ISSUE TITLE
Kebechet info

### ISSUE THREAD

**Issue by saisankargochhayat** [AICoE/prometheus-anomaly-detector#113]

**Comment by 4n4nd** [comment]
@saisankargochhayat something you need help with?

**Comment by saisankargochhayat** [comment]
@4n4nd  I think kebechet is not working on this repo, could you please check if @sesheta is added as a collaborator?

**Comment by 4n4nd** [comment]
I thought @harshad16 did provide write access to Sesheta [here](https://github.com/AICoE/prometheus-anomaly-detector/issues/72)

**Comment by saisankargochhayat** [comment]
@fridex We have this repo in our `AICoE.yaml` config, somehow its not visiting this repo?

**Comment by fridex** [comment]
> @fridex We have this repo in our `AICoE.yaml` config, somehow its not visiting this repo?

You can check logs in the aicoe-prod-bots namespace. There is a separate bot "kebechet-aicoe" handling just aicoe specific repositories.

**Comment by saisankargochhayat** [comment]
The logs say - 
`  File "/home/user/kebechet/managers/update/update.py", line 99, in _get_dependency_versionf"Failed to retrieve version information for dependency {dependency}, (dev: {is_dev})")kebechet.exception.InternalError: Failed to retrieve version information for dependency prometheus_client, (dev: False)`

The problem seems to be, in from Pipfile we are taking `prometheus_client`, where as in the Piplock its named as - `prometheus-client`
@fridex

**Comment by fridex** [comment]
> The logs say -
> ` File "/home/user/kebechet/managers/update/update.py", line 99, in _get_dependency_versionf"Failed to retrieve version information for dependency {dependency}, (dev: {is_dev})")kebechet.exception.InternalError: Failed to retrieve version information for dependency prometheus_client, (dev: False)`
> 
> The problem seems to be, in from Pipfile we are taking `prometheus_client`, where as in the Piplock its named as - `prometheus-client`
> Should we maybe replace underscores before looking in Piplock file?
> @fridex

This is related to Python package names normalization done in Pipfile/Pipefile.lock. Pipfile here states unnormalized package names (as provided by users), but Pipfile.lock states its normalized names.

Check PEP-503 and https://github.com/thoth-station/kebechet/issues/209

[1] https://www.python.org/dev/peps/pep-0503/#normalized-names
