### ISSUE TITLE
can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by ankit864** [AICoE/prometheus-anomaly-detector#122]
issue is happening when queue (multiprocessing.queue) is being used for train model function 

below is error
  
` ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects`

**Comment by yeswanthkaali** [comment]
Change the python version to higher or lower it worked for me.https://lists.gt.net/python/bugs/1299839

**Comment by ankit864** [comment]
thanks @yeswanthkaali , I had this  python issue in my knowledge as i was trying to troubleshoot, but I was running on macos  with  python 3.7 it was throwing bad file descriptor error  while accessing queue. 

so for workaround i used normal Queue instead of python MP queue but with thread not as multiporcess because normal queue cant be shared between process 

But in ubuntu with python37 it is  running fine.
