### ISSUE TITLE
How to get multiple timestep predictions into the future

### ISSUE THREAD

**Issue by tarakdatanow** [AICoE/prometheus-anomaly-detector#130]
Hi,

Which values/parameters are used to get multi-step output into the future? As per my understanding, currently I can only see 1 output value on the Tornado web app with four different vaues for each reading - yhat, yhat-lower, yhat-upper and anomaly.

How can I get multiple timesteps into future?

Example: Using last 100 days data, how can I predict for the next 10 days?

**Comment by 4n4nd** [comment]
> currently I can only see 1 output value on the Tornado web app

that's because these outputs are for Prometheus to scrape and the `anomaly` value can only be calculated using the current metric value

**Comment by tarakdatanow** [comment]
Okay, how should I get the forecasting for multiple input timeseries?
Also, how can I plot it on a dashboard just as you've shown in your examples in the Readme?

**Comment by 4n4nd** [comment]
You can use Grafana to plot metrics once the predicted metrics are scraped by the Prometheus instance

**Comment by chiaminchuang** [comment]
Hello @tarakdatanow, I have the same issue. Do you solve this problem? Thanks in advance.


> You can use Grafana to plot metrics once the predicted metrics are scraped by the Prometheus instance

Hello @4n4nd ,
In the source code, the Prometheus instance scrapes one prediction whose timestamp is closest to the current timestamp. We cannot plot the metrics on the Grafana dashboard. 
How do we make the Prometheus instance scrape the future predictions not only the most recent one?

Thank you for your great repo.
