### ISSUE TITLE
Not getting yhat values in the output

### ISSUE THREAD

**Issue by tarakdatanow** [AICoE/prometheus-anomaly-detector#131]
Hi,

I tried this repo a while ago and it was giving me some yhat values in the output, but now its not showing. The output looks something like this:

````
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 19576.0
python_gc_objects_collected_total{generation="1"} 13679.0
python_gc_objects_collected_total{generation="2"} 4193.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 514.0
python_gc_collections_total{generation="1"} 52.0
python_gc_collections_total{generation="2"} 4.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="6",patchlevel="10",version="3.6.10"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 4.57629696e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.15408896e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.59958778088e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.01
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 15.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
```
`

What could be the possible reason?

**Comment by 4n4nd** [comment]
@tarakdatanow Could you check your Promtheus instance if it has the metric that you are trying to predit?

**Comment by tarakdatanow** [comment]
Thanks @4n4nd I was sending a wrong ID in the metrics. But now I'm facing a new issue. Can you tell what this would mean:

```
File "/home/tarak/Desktop/prometheus_new/prometheus-anomaly-detector/app.py", line 77, in get
    for predictor_model in self.settings["model_list"]:
KeyError: 'model_list'
2020-09-09 00:07:52,102:ERROR:tornado.access: 500 GET / (127.0.0.1) 80.38ms
2020-09-09 00:07:53,820:ERROR:tornado.application: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/tarak/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/home/tarak/Desktop/prometheus_new/prometheus-anomaly-detector/app.py", line 77, in get
    for predictor_model in self.settings["model_list"]:
KeyError: 'model_list'
2020-09-09 00:07:53,821:ERROR:tornado.access: 500 GET / (127.0.0.1) 1.81ms
```

**Comment by 4n4nd** [comment]
@tarakdatanow this is weird, Could you please try a simple metric like `up` which we know has constant metric values available?

**Comment by 4n4nd** [comment]
@tarakdatanow Could you try again after updating the dependencies to their latest versions?
#132 this was a similar issue

**Comment by 4n4nd** [comment]
@tarakdatanow The issue with publishing forecasts is:
1. We need the current actual value of a metric to calculate if that value is anomalous.
2. Prometheus does not support (by feature) scraping future metric values

nonetheless the metric values are predicted in this application and are stored as a timeseries dataframe named `forecast` ([here](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/model.py#L56)), you should be able to access the predicted values using that dataframe.

**Comment by tarakdatanow** [comment]
I'm again confused @4n4nd what is anomaly flag used for then? Is there any possibility of it becoming 1.0 depending upon the type of forecast?

 ```
                                   yhat  yhat_lower  yhat_upper
timestamp                                                       
2020-09-16 09:04:57.026000023  52.995022   41.955735   63.360317
2020-09-16 09:05:57.026000023  52.978287   42.725903   64.723872
2020-09-16 09:06:57.026000023  52.962429   41.977058   63.723740
2020-09-16 09:07:57.026000023  52.947475   41.646314   63.756094
2020-09-16 09:08:57.026000023  52.933452   42.107426   64.021965
2020-09-16 09:09:57.026000023  52.920387   43.012837   63.727821
2020-09-16 09:10:57.026000023  52.908306   41.519156   63.264446
2020-09-16 09:11:57.026000023  52.897235   42.702340   64.024837
2020-09-16 09:12:57.026000023  52.887199   42.841128   63.254900
2020-09-16 09:13:57.026000023  52.878225   41.947104   63.398739
```

Let's take for example I'm using 10 mins of retraining interval. So, I'm getting 10 mins of forecasts in the forecasts as shown above. So correct me if I'm wrong - the anomaly detection used to indicate whether there's an anomaly in this time period, right?

**Comment by 4n4nd** [comment]
@tarakdatanow the anomaly detection is for checking if the real metric is acting weird (anomalous). 
So for example you could use it on a metric like cpu usage, and the anomaly flag should be 1 when the cpu usage is unusual. 

How we do that is, we calculate the yhat_upper and yhat_lower bounds and if the real metric value goes out of these bounds, it is considered anomalous.

**Comment by tarakdatanow** [comment]
![Screenshot from 2020-10-07 21-57-35](https://user-images.githubusercontent.com/65151788/95758167-b635c580-0cc5-11eb-9df9-40165227845a.png)
![Screenshot from 2020-10-07 21-53-51](https://user-images.githubusercontent.com/65151788/95758174-b7ff8900-0cc5-11eb-933e-d35285fa5978.png)

I got the four values on the dashboard, however, why is my anomaly flag becoming 0 even though my yhat value is between yhat-lower and yhat-upper?

**Comment by 4n4nd** [comment]
yhat should always be between yhat_upper and yhat_lower. It will be an anomaly if the actual metric value (in this case `device_metric{}`) goes out of these bounds. 
Anomaly flag being 0 means there is not an anomaly. It will be 1 when the real metric value goes out of the predicted bounds.

**Comment by tarakdatanow** [comment]
Let's take an example, 
my time stamp is - 2020-09-16 09:04:57 and my retraining interval is 10 mins, so, for the next 10 mins there won't be a check for whether there's an anomaly or not and the 10 sub-readings of frequency of 1 minute each are useless as I mentioned in the previous thread?

When 10 mins are elapsed, the code will again start retraining the model and I'll get a new table with 10 values in it.

So, you're saying that these 10 predictions are of no use?

And I can only say whether there's an anomaly or not, right? I'm still confused!

**Comment by tarakdatanow** [comment]
> ![Screenshot from 2020-10-07 21-57-35](https://user-images.githubusercontent.com/65151788/95758167-b635c580-0cc5-11eb-9df9-40165227845a.png)
> ![Screenshot from 2020-10-07 21-53-51](https://user-images.githubusercontent.com/65151788/95758174-b7ff8900-0cc5-11eb-933e-d35285fa5978.png)
> 
> I got the four values on the dashboard, however, why is my anomaly flag becoming 0 even though my yhat value is between yhat-lower and yhat-upper?

If you'll see closely, my yhat is within the bounds but my anomaly flag is changing from 1 to 0. That's what I want to understand. How did it go from 1 to 0 while the values were always between the lower and upper bounds?

**Comment by tarakdatanow** [comment]
> yhat should always be between yhat_upper and yhat_lower. It will be an anomaly if the actual metric value (in this case `device_metric{}`) goes out of these bounds.
> Anomaly flag being 0 means there is not an anomaly. It will be 1 when the real metric value goes out of the predicted bounds.
> 
> Can you also plot the actual metric so we can compare it?

How to plot actual metric here?

**Comment by 4n4nd** [comment]
> Let's take an example,
> my time stamp is - 2020-09-16 09:04:57 and my retraining interval is 10 mins, so, for the next 10 mins there won't be a check for whether there's an anomaly or not and the 10 sub-readings of frequency of 1 minute each are useless as I mentioned in the previous thread?
> 
> When 10 mins are elapsed, the code will again start retraining the model and I'll get a new table with 10 values in it.
> 
> So, you're saying that these 10 predictions are of no use?
> 
> And I can only say whether there's an anomaly or not, right? I'm still confused!

It will check if the current metric (the real metric not the predicted yhat) is anomalous every time the prometheus tries to scrape PAD (here it might be 1 min). This is where it uses the predicted 10 values.

> If you'll see closely, my yhat is within the bounds but my anomaly flag is changing from 1 to 0. That's what I want to understand. How did it go from 1 to 0 while the values were always between the lower and upper bounds?

`yhat`,`yhat_upper` and `yhat_lower` are all predicted values. The upper and lower bounds are calculated using yhat. So yhat will always be between yhat_upper and yhat_lower.

**Comment by 4n4nd** [comment]
> How to plot actual metric here?

your real metric is the `FLT_METRICS_LIST` parameter that you set in in your PAD configuration. 

I suggest you use [Grafana](https://github.com/grafana/grafana) for Promtheus metrics visualization.

**Comment by darox** [comment]
It seems working on my side, but I can't find the predicted value in prometheus. My current output is:
```
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
2020-11-08 11:54:53,166:INFO:__main__: Total Training time taken = 0:01:08.898653, for metric: node_network_receive_bytes_total {'device': 'vmx1', 'instance': 'fw-opnsense-1.damn.li:9100', 'job': 'node_exporer'}
2020-11-08 11:54:53,168:INFO:__main__: Initializing Tornado Web App
2020-11-08 11:54:53,188:INFO:__main__: Will retrain model every 15 minutes
```
