### ISSUE TITLE
getpwuid error

### ISSUE THREAD

**Issue by JeongChanwoo** [AICoE/prometheus-anomaly-detector#135]
I configured the docker compose file and ran test_model.py. However, at the stage of starting mlflow, the result is that there is no 1001 in getpwuid(). I am curious about whether the problem has been previously reported, and if there is any reported content, I am curious about a solution.
Below is my error message.

Traceback (most recent call last):
   File "test_model.py", line 110, in <module>
    mlflow.start_run()
   File "/opt/conda/envs/prophet-env/lib/python3.8/site-packages/mlf
    tags = context_registry.resolve_tags(user_specified_tags)
   File "/opt/conda/envs/prophet-env/lib/python3.8/site-packages/mlf
     all_tags.update(provider.tags())
   File "/opt/conda/envs/prophet-env/lib/python3.8/site-packages/mlf
    MLFLOW_USER: _get_user(),
   File "/opt/conda/envs/prophet-env/lib/python3.8/site-packages/mlf
     return getpass.getuser()
  File "/opt/conda/envs/prophet-env/lib/python3.8/getpass.py", line
     return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1001'

**Comment by 4n4nd** [comment]
Can you please show me how you built the container image?

**Comment by JeongChanwoo** [comment]
Here's my docker-compose configuration.
version: '3'
services:
  anoma_test:
    image : quay.io/4n4nd/prometheus-anomaly-detector:latest
    environment:
      - TZ=Asia/Seoul
      - APP_FILE=test_model.py
      - FLT_PROM_URL={my_own prometheus server}
      - FLT_RETRAINING_INTERVAL_MINUTES=20
      - FLT_METRICS_LIST=another_metric{exported_instance='some_instance',exported_job='some_job',instance='mkseoul.iptime.org:6074',job='some_job'}; some_metric{exported_instance='some_instance',exported_job='some_job',instance='mkseoul.iptime.org:6074',job='some_job',label='val1'}
      - FLT_ROLLING_TRAINING_WINDOW_SIZE=1d
      - FLT_DATA_START_TIME="2020-10-20 18:00:00"
      - FLT_DATA_END_TIME="2020-10-21 22:00:00"
      - MLFLOW_TRACKING_URI={my_own mlflow tracking server}
    ports:
      - "{forwarding port}:8080"



``

**Comment by JeongChanwoo** [comment]
@4n4nd 
Here's my docker-compose configuration.


version: '3'
services:
anoma_test:
image : quay.io/4n4nd/prometheus-anomaly-detector:latest
environment:
- APP_FILE=test_model.py
- FLT_PROM_URL={my_own prometheus server}
- FLT_RETRAINING_INTERVAL_MINUTES=20
- FLT_METRICS_LIST=another_metric{exported_instance='some_instance',exported_job='some_job',instance={instance},job='some_job'}; some_metric{exported_instance='some_instance',exported_job='some_job',instance={instance},job='some_job',label='val1'}
- FLT_ROLLING_TRAINING_WINDOW_SIZE=1d
- FLT_DATA_START_TIME="2020-10-20 18:00:00"
- FLT_DATA_END_TIME="2020-10-21 22:00:00"
- MLFLOW_TRACKING_URI={my_own mlflow tracking server}

ports:
- "{forwarding port}:8080"

**Comment by 4n4nd** [comment]
I was able to fix this issue by running the container image as user `nobody`.
you will have to add `user: nobody` in your anoma_test service.

Just for reference, I used the following command to run the test:
`docker run --name pad -p 127.0.0.1:8080:8080 --user nobody --network host --env FLT_PROM_URL=http://demo.robustperception.io:9090 --env FLT_RETRAINING_INTERVAL_MINUTES=60 --env FLT_METRICS_LIST='up{instance="demo.robustperception.io:9090",job="prometheus"}' --env APP_FILE=test_model.py --env MLFLOW_TRACKING_URI=http://127.0.0.1:5000 --env FLT_DATA_START_TIME=3d --env FLT_DATA_END_TIME=now quay.io/aicoe/prometheus-anomaly-detector:latest`

**Comment by JeongChanwoo** [comment]
Thanks @4n4nd . 
I was able to solve the problem by adding '--user nobody' as you described.

**Comment by 4n4nd** [comment]
Awesome! I will close this issue now. If you have any more questions please feel free to open a new issue or just reopen this one.
