### ISSUE TITLE
multivariate time-series data supporting

### ISSUE THREAD

**Issue by JeongChanwoo** [AICoE/prometheus-anomaly-detector#137]
Currently, PAD models and environments seem to be constructed based on a single variable.
I am wondering if there is any other way to configure multivariate time-series data model and predict.
If not, I wonder if it will reflect the configuration of functions supporting multivariate time-series data in the future.

**Comment by 4n4nd** [comment]
@JeongChanwoo I don't think any of our models support multi-variate time series by default. 

If you just want to predict multiple time series individually, you can do so by separating the metric names using a `;` in the [Configuration](https://github.com/AICoE/prometheus-anomaly-detector#configurations).
