### ISSUE TITLE
PAD & ml_flow tag issue

### ISSUE THREAD

**Issue by JeongChanwoo** [AICoE/prometheus-anomaly-detector#138]
After changing the model to lstm in the test_model.py file, I tried to proceed. However, when checked in mlflow, the model tag of the experiment is fixed as prophet.

I have changed to the lstm model, but I am worried that the learning and predictions are not fixed as a prophet.

Even if I changed to the Fourier transform model, the prophet model tag is displayed fixedly.

**Comment by 4n4nd** [comment]
@JeongChanwoo I checked the `test_model.py` ([here](https://github.com/AICoE/prometheus-anomaly-detector/blob/master/test_model.py#L114)) it looks like the model name is being imported directly from the model file. Could you check if the correct model file was imported?

Maybe if you are using a container image, make sure you rebuild rebuild the image so the changes that you make are available in the image.
