### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by saswat0** [AICoE/prometheus-anomaly-detector#144]
I was trying to run the application by running the app.py file for my kubernetes cluster
`python app.py`

Configuration:

- prometheus_url = 'http://thanos.xxxxxx' 
- metrics_list = `["container_cpu_usage_seconds_total{kube_cluster=~'k8s2.xxxxx',namespace='xxx',pod=~'xxxxx-.*'}"]`
- rolling_training_window_size = parse_timedelta("now", "1d")
- retraining_interval_minutes = 15

The metric is pretty small (7 iterations) and hence takes very less time to train. Upon completion, I get this error:
`500: Internal Server Error` at localhost:8080

Logs from the python terminal are as follows:

>   File "/home/ubuntu/anaconda3/envs/prophet-env/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "app.py", line 90, in get
    GAUGE_DICT[metric_name].labels(
  File "/home/ubuntu/anaconda3/envs/prophet-env/lib/python3.8/site-packages/prometheus_client/metrics.py", line 160, in labels
    raise ValueError('Incorrect label names')
ValueError: Incorrect label names
2021-05-10 15:34:50,598:ERROR:tornado.access: 500 GET /metrics (127.0.0.1) 91.04ms

Please assist me in resolving this

**Comment by 4n4nd** [comment]
[This](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L160) is where the error is being raised at.
@saswat0 can you try this again without the regex identifiers? I have never seen this issue before.
Does the same issue happen for different metrics as well?

**Comment by saswat0** [comment]
@4n4nd I tried using numOfRequests as metric and got this output at port 8080

> # HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 9444.0
python_gc_objects_collected_total{generation="1"} 1063.0
python_gc_objects_collected_total{generation="2"} 21.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 2601.0
python_gc_collections_total{generation="1"} 238.0
python_gc_collections_total{generation="2"} 21.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="8",version="3.8.8"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.162305536e+09
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.64654336e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.6206669842e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.83
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 18.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
# HELP numOfRequests_prophet Forecasted value from Prophet model
# TYPE numOfRequests_prophet gauge
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="GET",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat"} 159405.05472916208
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="GET",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_lower"} 159368.6239108586
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="GET",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_upper"} 159444.98308404404
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="GET",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="anomaly"} 0.0
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="OPTIONS",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat"} 171.3287219909277
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="OPTIONS",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_lower"} 168.14249367819318
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="OPTIONS",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_upper"} 174.44040163000813
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="OPTIONS",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="anomaly"} 0.0
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="POST",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat"} 27651.260827850336
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="POST",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_lower"} 27633.834762853352
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="POST",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat_upper"} 27669.344882702044
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-dbkjf",method="POST",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="anomaly"} 0.0
numOfRequests_prophet{app="prod-lfca-some-name",env="prod",instance="ip-node-ip-address.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx.io",kubernetes_namespace="namespace-name",kubernetes_pod_name="prod-lfca-some-name-57484b67f8-ftl94",method="GET",monitor="k8s2.xxxxx.io",ondemand="true",pod_template_hash="57484b67f8",project="consumer-application-demo",region="ap-southeast-1",servicePriority="p0",stack="1",team="team_name",value_type="yhat"} 173170.40699114255

**Comment by 4n4nd** [comment]
@saswat0 could you please show me all the labels/values for the metric that break it?

**Comment by saswat0** [comment]
I'm sorry, I didn't get you there.
Should I list down all the metrics for which this is failing?

**Comment by saswat0** [comment]
Any pointers as to how I could try out all the label_metrics for a particular metric
Currently I'm not passing any particular label_metric to the config.

This is how my metrics_list looks like in different cases:

- ["container_cpu_usage_seconds_total"]
- ["numOfRequests"]
- ["http_requests_total"]

**Comment by saswat0** [comment]
For container_cpu_usage_seconds_total
> container_cpu_usage_seconds_total{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_instance_type="c5.large",beta_kubernetes_io_os="linux",container="POD",cpu="total",env="prod",failure_domain_beta_kubernetes_io_region="ap-southeast-1",failure_domain_beta_kubernetes_io_zone="ap-southeast-1a",id="/kubepods/besteffort/pod8e096232-08cf-488e-af51-c447d1dbefec/d0c15b5ebec7afbfd8bf6785d29a854868dabae38463dd5b98058133229b5271",image="k8s.gcr.io/pause-amd64:3.2",instance="ip-10-25-13-48.ap-southeast-1.compute.internal",job="workers.k8s.cadvisor",kops_k8s_io_instancegroup="master-ap-southeast-1a",kube_cluster="devops-k8s0.xxxxx",kubernetes_io_arch="amd64",kubernetes_io_hostname="ip-10-25-13-48.ap-southeast-1.compute.internal",kubernetes_io_os="linux",kubernetes_io_role="master",monitor="devops-k8s0.xxxxx",name="k8s_POD_istio-cni-node-jls59_istio-system_8e096232-08cf-488e-af51-c447d1dbefec_0",namespace="istio-system",node_kubernetes_io_instance_type="c5.large",pod="istio-cni-node-jls59",region="ap-southeast-1",topology_kubernetes_io_region="ap-southeast-1",topology_kubernetes_io_zone="ap-southeast-1a"}

For numOfRequests
> numOfRequests{app="prod-some-name",env="prod",instance="ip-10-50-117-148.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx",kubernetes_namespace="namespace",kubernetes_pod_name="prod-some-name-7879d6b46b-km8qs",method="GET",monitor="k8s2.xxxxx",ondemand="true",pod_template_hash="7879d6b46b",project="consumer-web",region="ap-southeast-1",servicePriority="p0",stack="1",team="namespace"}

http_requests_total
> http_requests_total{app="elastic-exporter",code="200",env="prod",handler="prometheus",instance="ip-10-50-126-20.ap-southeast-1.compute.internal",job="pods.k8s",kube_cluster="k8s2.xxxxx",kubernetes_namespace="monitoring",kubernetes_pod_name="elastic-exporter-c6768dfd5-d67q7",method="get",monitor="k8s2.xxxxx",pod_template_hash="c6768dfd5",region="ap-southeast-1",team="devops"}

**Comment by 4n4nd** [comment]
Now can you please try using these "full" queries in your anomaly detector config?

**Comment by saswat0** [comment]
When I do this, it gets nothing to train on

Terminal logs:

> `
2021-05-11 16:15:46,498:INFO:configuration: Metric data rolling training window size: 23:59:59.970879
2021-05-11 16:15:46,498:INFO:configuration: Model retraining interval: 15 minutes
2021-05-11 16:15:46,646:DEBUG:urllib3.connectionpool: Starting new HTTP connection (1): k8s-2.prometheus.xxxxxx:9090
2021-05-11 16:15:46,663:DEBUG:urllib3.connectionpool: http://k8s-2.prometheus.xxxxxx:9090 "GET //api/v1/query?query=http_requests_total%7Bapp%3D%22elastic-exporter%22%2Ccode%3D%22200%22%2Cenv%3D%22prod%22%2Chandler%3D%22prometheus%22%2Cinstance%3D%22ip-10-50-126-20.ap-southeast-1.compute.internal%22%2Cjob%3D%22pods.k8s%22%2Ckube_cluster%3D%22k8s2.xxxxxx%22%2Ckubernetes_namespace%3D%22monitoring%22%2Ckubernetes_pod_name%3D%22elastic-exporter-c6768dfd5-d67q7%22%2Cmethod%3D%22get%22%2Cmonitor%3D%22k8s2.xxxxxx%22%2Cpod_template_hash%3D%22c6768dfd5%22%2Cregion%3D%22ap-southeast-1%22%2Cteam%3D%22devops%22%7D HTTP/1.1" 301 558
2021-05-11 16:15:46,666:DEBUG:urllib3.connectionpool: http://k8s-2.prometheus.xxxxxx:9090 "GET /api/v1/query?query=http_requests_total%7Bapp%3D%22elastic-exporter%22%2Ccode%3D%22200%22%2Cenv%3D%22prod%22%2Chandler%3D%22prometheus%22%2Cinstance%3D%22ip-10-50-126-20.ap-southeast-1.compute.internal%22%2Cjob%3D%22pods.k8s%22%2Ckube_cluster%3D%22k8s2.xxxxxx%22%2Ckubernetes_namespace%3D%22monitoring%22%2Ckubernetes_pod_name%3D%22elastic-exporter-c6768dfd5-d67q7%22%2Cmethod%3D%22get%22%2Cmonitor%3D%22k8s2.xxxxxx%22%2Cpod_template_hash%3D%22c6768dfd5%22%2Cregion%3D%22ap-southeast-1%22%2Cteam%3D%22devops%22%7D HTTP/1.1" 200 87

0it [00:00, ?it/s]
2021-05-11 16:15:46,670:INFO:__main__: Initializing Tornado Web App
2021-05-11 16:15:46,671:DEBUG:asyncio: Using selector: EpollSelector
2021-05-11 16:15:46,676:INFO:__main__: Will retrain model every 15 minutes
2021-05-11 16:16:34,802:INFO:tornado.access: 200 GET / (127.0.0.1) 2.58ms
2021-05-11 16:16:35,030:WARNING:tornado.access: 404 GET /favicon.ico (127.0.0.1) 0.57ms
`

Output at localhost:8080

> `
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 1619.0
python_gc_objects_collected_total{generation="1"} 318.0
python_gc_objects_collected_total{generation="2"} 9.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 368.0
python_gc_collections_total{generation="1"} 35.0
python_gc_collections_total{generation="2"} 3.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="8",version="3.8.8"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.61913344e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.2731008e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.62074974667e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.0
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 17.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
`

**Comment by saswat0** [comment]
Also, I had one concern. This full metric will point to a single pod. How can I apply it over all the pods/services? Do I need to scrape all the metrics and then append each of them to the `metrics_list` list? Would that not be invalid? (Assuming that the pod could've been dead at some point)

**Comment by 4n4nd** [comment]
I think what the issue here is that you have 2 (or more) different metrics which don't have a unique label configuration, 
example: `metric_1{a=1, b=2}` and `metric_1{a=1, b=2, c=3}`, 
and that's why I wanted your query to be as specific so that only unique time-series are collected.

**Comment by saswat0** [comment]
So I need to set these label metrics to some keys that will be present in all the metrics, right?

**Comment by 4n4nd** [comment]
Yes, exactly

**Comment by 4n4nd** [comment]
> So numOfRequests is working fine as per the prediction is concerned, isn't it?

Yep that is the expected output.

> Another doubt. Is the output that I'm getting at localhost:8080 here expected? Or should I be getting any plots for this?

So the data exposed here is in format that is scrape-able by prometheus, so you will need to configure a prometheus instance to scrape this endpoint and store data. Once you do that, you can visualize the data better in the prometheus console or you can add grafana for it.

**Comment by saswat0** [comment]
Okay, got you 👍 
Now for assigning metrics, should I assign metric_1{a=1, b=2} or metric_1{a=1, b=2, c=3}? If I assign the second one, will I not miss out on those that do not have 'c' label?

**Comment by 4n4nd** [comment]
that is a good question, but I think you can have specific queries that will look for an empty metric label. 
Example: `metric_1{c=""}` that will check for empty values of `c`

**Comment by saswat0** [comment]
Alright then. I'll look into this
I'm getting a bit stuck in the testing (prediction) part. My y_hat is nearly equal to the actual value but is diverging at a high pace. Also, it is well beyond the interval of [yhat_lower to yhat_upper]. I'm currently training on 30 days data and am using this as my metric `nginx_ingress_controller_request_size_sum{controller_class="top-nginx-public",status=~"5[0-9][0-9]"}`
<img width="1297" alt="Screenshot 2021-05-12 at 9 49 34 PM" src="https://user-images.githubusercontent.com/32325136/118009847-11b75700-b36c-11eb-8f0c-dedca02ea64a.png">

If the metric is nginx_ingress_controller_request_size_sum, what is the significance of nginx_ingress_controller_request_size_sum_prophet? The values reported by these two are significantly different

**Comment by 4n4nd** [comment]
@saswat0 we are using facebook's [prophet model](https://github.com/facebook/prophet) by default for metric prediction. You can check their [repo](https://github.com/facebook/prophet) to look into how it works under the hood.

**Comment by saswat0** [comment]
Sure. I'll look into that
The '_prophet' suffix is defined [here](https://github.com/AICoE/prometheus-anomaly-detector/blob/20dc284b86b0b6e0cb9990679defe1735d8fd9f3/app.py#L50). What insight does it give us?

Here are the plots that I got today. The model behaves awkwardly with my provided data. Would you be able to provide me some pointers as to how I can debug it?
<img width="1080" alt="Screenshot 2021-05-13 at 10 55 45 PM" src="https://user-images.githubusercontent.com/32325136/118162431-5c090880-b43e-11eb-935c-ac3b637e47c9.png">
