### ISSUE TITLE
Can not choose training model and build docker image error

### ISSUE THREAD

**Issue by zanghao2** [AICoE/prometheus-anomaly-detector#148]
I found that the project provides three training models but I can not choose which model to use. When I change model I must rebuild the image. I think it is necessary to provide access to the three models.

I use docker to build image, when I run my build image I found tensorflow not found error.

**Comment by arjunshenoymec** [comment]
Same here (https://pastebin.com/J2ctTDEA). 

@4n4nd are we missing any configs/steps here?
