### ISSUE TITLE
Add ability to ignore labels 

### ISSUE THREAD

**Issue by HumairAK** [AICoE/prometheus-anomaly-detector#155]
The way I understand it, PAD will need to be restarted whenever a label updates. This is an issue for when dealing with metrics that contain pod names as a label for example. If the pod has a generated suffix, a new one is generated upon each restart, thus requiring pad to be restarted, and being unable to leverage the old pod's historical data (iiuc). 

It would be nice if I could pass a flag or file with a list of labels to ignore :)

**Comment by 4n4nd** [comment]
This is a great suggestion.
 I think we could add a new flag something like
`FLT_IGNORE_LABEL_CHANGES="pod_name, pod_ip"` and it would ignore the changes in those specific labels.
