### ISSUE TITLE
The value predicted by Prophet did not change much

### ISSUE THREAD

**Issue by lynBIT** [AICoE/prometheus-anomaly-detector#179]
The value predicted by Prophet did not change much

Here are my variable settings：
FLT_PROM_URL = http://xx:xx:xx:xx:30090
FLT_PROM_ACCESS_TOKEN = xxxxx;
FLT_METRICS_LIST = node_load1{instance='192.29.3.11:9100'};
FLT_RETRAINING_INTERVAL_MINUTES = 15;
FLT_ROLLING_TRAINING_WINDOW_SIZE = 20d;
FLT_PARALLELISM= 2;

I have deployed the anomaly detection service on k8s, and my prometheus can also discover the anomaly detection target。

However, I found that the yhat of the metrics output by anomaly detection is basically stable at around 0.6, and does not change with the original data.
The figure below is the predicted metrics versus the original metrics in grafana
![image](https://user-images.githubusercontent.com/43242489/164618507-e6db49a6-a8ae-4d5b-bc8f-8b4f01bbb113.png)
Green bar is :  node_load1{instance='192.29.3.11:9100'}  (origin metrics)
yellow Bar is : yhat.
Orange Bar is :yhat_upper
Sky blue bar is : yhat_lower
Red Bar is : anomaly

How should I adjust the prophet parameters, or is there any other way to make Prophet predict the value accurately？
please help me

**Comment by LOTFIChaimaa** [comment]
Please, can we have a call to discuss about the set up of the environment

**Comment by lynBIT** [comment]
> 

That is to say, I have the above problem because of the wrong environment configuration?

**Comment by lynBIT** [comment]
> Please, can we have a call to discuss about the set up of the environment

That is to say, I have the above problem because of the wrong environment configuration?

**Comment by LOTFIChaimaa** [comment]
not really, I just want to ask about something in the environment configuration, if you have a lit bit of time

**Comment by lynBIT** [comment]
> 



> not really, I just want to ask about something in the environment configuration, if you have a lit bit of time

You can ask here and I will try to help you if I know

**Comment by LOTFIChaimaa** [comment]
like they said that we have to launch the app with python app.py and we can use make run_app, while these two files are not in the repository so!!??
