### ISSUE TITLE
test_model should give the user ability to define date and time of testing interval 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/prometheus-anomaly-detector#34]
`test_model.py` should include options that allow a user to dictate the exact start and end time of their testing window. 

Current implementation takes rolling data window size in days and the current time automatically. This is an OK default, but we should also give the user the ability to specify specific time periods where they know an anomaly has occurred for testing purposes.

**Comment by MichaelClifford** [comment]
To address @4n4nd's request in #35, below are the specific inputs we should add in our `.env` to achieve a user defined time range.

FLT_TEST_START_TIME = " "
FLT_TEST_END_TIME = "  "

These two values will dictate the  `start_time` and `end_time` for the data downloaded when running `test_model.py` :https://github.com/AICoE/prometheus-anomaly-detector/blob/4f942677f347ea9aea122e3aebb4331b070a6ac2/test_model.py#L70-L94

**Comment by 4n4nd** [comment]
Does it test on all this test data once? or do we specify a training interval?

**Comment by MichaelClifford** [comment]
So I think we still specify the training interval. It should be the same value as `FLT_ROLLING_DATA_WINDOW`. maybe this could be renamed for clarity? maybe `FLT_ROLLING_TRAINING_WINDOW`?

**Comment by 4n4nd** [comment]
okay `FLT_ROLLING_TRAINING_WINDOW` sounds good.
`FLT_TEST_START_TIME`
`FLT_TEST_END_TIME`

and maybe `FLT_TRAIN_START_TIME` and `FLT_TRAIN_END_TIME` as well?

**Comment by MichaelClifford** [comment]
Yes, `FLT_TEST_START_TIME` and `FLT_TEST_END_TIME` should specify the total data used by `model_test.py`. 

`FLT_RETRAINING_INTERVAL_MINUTES` should specify the prediction range for the test (how far into the future we will forecast after each retraining) , as it represents how frequently we will retrain the model on the `FLT_ROLLING_TRAINING_WINDOW` timeframe and then make our forecast up to the next retraining. 

I don't think we need `FLT_TRAIN_START_TIME` and `FLT_TRAIN_END_TIME`.

**Comment by 4n4nd** [comment]
Okay I will add,
* `FLT_DATA_START_TIME`: Data start time
* `FLT_DATA_END_TIME`: Data End time
* `FLT_ROLLING_TRAINING_WINDOW_SIZE`: Training data window size
* `FLT_RETRAINING_INTERVAL_MINUTES`: retraining interval/ forecasting duration

**Comment by goern** [comment]
heya, what needs to be done to close this?
