### ISSUE TITLE
ConfigQuestion "cannot import name 'Metric' from 'prometheus_api_client'"

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#75]
Hi @all,

while testing this tool I ran into an Syntax Error in a very early stage of testing.

The environment variables were set:

host:~/prometheus-anomaly-detector-master # echo $FLT_RETRAINING_INTERVAL_MINUTES ; echo $FLT_ROLLING_TRAINING_WINDOW_SIZE ; echo $FLT_METRICS_LIST; echo $FLT_PROM_URL
5
1d
up{vsphere_disk_maxtotallatency_latest{host=esx20b}};
http://promhost.domain.de:9090

But if I start the app I get this error:

host:~/prometheus-anomaly-detector-master # /usr/local/bin/python3.7  app.py
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    from prometheus_api_client import PrometheusConnect, Metric
ImportError: cannot import name 'Metric' from 'prometheus_api_client' (/usr/local/lib/python3.7/site-packages/prometheus_api_client/__init__.py)

With tcpdump I could not see packets between my host and promhost.domain.de. With w3m I can connect to http://promhost.domain.de:9090 without problems.

Can anyone give me a hint how I can troubleshoot this issue ?

Bye, Dirk

**Comment by 4n4nd** [comment]
I think that means the version of `prometheus-api-client`, installed is not the newest. 
This might be an issue on our side, we need to update our Pipfile here.

Until then, can you just install the library directly from source by running:
`pip install https://github.com/AICoE/prometheus-api-client-python/zipball/v0.0.2`

I think this should fix the issue.

**Comment by 4n4nd** [comment]
@DirkFries The dependencies for this should be updated now, I will close this issue. If you still have any problems please feel free to reopen it.
Thanks
