### ISSUE TITLE
how to visualization yhat_upper, yhat_lower, original metric value, predicted matric value and the anomaly?

### ISSUE THREAD

**Issue by spinnetechnology** [AICoE/prometheus-anomaly-detector#81]
Dear All,

I am newbie and trying to implement this tools to have prediction on oracle database processes.
Below is my setting:
-------------
My env file:
-------------
FLT_PROM_URL=http://localhost:9090
FLT_METRICS_LIST=oracledb_process_count{instance='localhost:9161'}
FLT_RETRAINING_INTERVAL_MINUTES=15
FLT_ROLLING_TRAINING_WINDOW_SIZE=30D
mlflow_tracking_uri=http://127.0.0.1:5000

I execute following command:
pipenv run python3 app.py

I got the following log:
2019-10-29 12:07:52,342:INFO:apscheduler.executors.default: Job "train_model (trigger: interval[0:15:00], next run at: 2019-10-29 12:22:52 WIB)" executed successfully

How I can see the result as stated on the document, yhat_upper, yhat_lower, original metric value, predicted matric value and the anomaly? I can not find these metrics on Prometheus as well as on grafana.

I hope somebody can show me where to go..

Thanks

**Comment by 4n4nd** [comment]
Oh so what PAD does is, it starts a new web server on port 8080 and it publishes the results as a Prometheus target. You can just go to http://localhost:8080/metrics and should be able to see the predicted values. The best way to look at the results would be to add http://localhost:8080/metrics as a scraping target to your Prometheus, that way you can can visualize the predicted metrics with the original metrics.

Hope this helps!

**Comment by spinnetechnology** [comment]
Thanks for your quick response and the information.
I got this information from http://localhost:8080/metrics.

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 30025.0
python_gc_objects_collected_total{generation="1"} 19137.0
python_gc_objects_collected_total{generation="2"} 1186.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 520.0
python_gc_collections_total{generation="1"} 56.0
python_gc_collections_total{generation="2"} 4.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="6",patchlevel="8",version="3.6.8"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.46456576e+09
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.74850048e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.57198726245e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 9.850000000000001
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 13.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0

it seem I have miss something here..
I did not get the yhat_upper, yhat_lower, original metric value, predicted matric value and the anomaly

**Comment by 4n4nd** [comment]
hmmm this is weird. Can you make sure if this query is correct? oracledb_process_count{instance='localhost:9161'}
It might be that the PAD did not get any metric data to train on

**Comment by 4n4nd** [comment]
If that doesn't work, try turning on the debug mode by setting FLT_DEBUG_MODE to True

**Comment by spinnetechnology** [comment]
Thank you very much. You are right, I need to change the parameter from FLT_METRICS_LIST=oracledb_process_count{instance='localhost:9161'}
to
oracledb_process_count{instance="10.255.20.69",job="oracle-short01"}
and 
add metric on Prometheus.yml for ternado.
so. I just put original metrics from Prometheus and from tornado on grafana. Incredible it work.

Big thanks for u.
