### ISSUE TITLE
Something similar but to find co-relation between multiple metrics

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-anomaly-detector#9]
Instead of anomaly detector, you could just change the model to find co-relation between a list of metrics passed as a parameter. It might be a completely different application but the base structure is very similar to this one. 
The output from this new application would be a heatmap of co-relation values for each metric combination.

**Comment by durandom** [comment]
yes, subhojit was looking into something similar and there are some notebooks about this somewhere :)
