### ISSUE TITLE
ImportError: No module named prometheus_api_client.utils

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#96]
Hi @all,

while trying to get the latest version running I encountered an error:

```
host:~/prometheus-anomaly-detector-master # python test_model.py
Traceback (most recent call last):
  File "test_model.py", line 4, in <module>
    from prometheus_api_client import PrometheusConnect, MetricsList, Metric
ImportError: No module named prometheus_api_client
```

Same happens when I try to test my configuration:

```
host:~/prometheus-anomaly-detector-master # python test_configuration.py
Traceback (most recent call last):
  File "test_configuration.py", line 4, in <module>
    from prometheus_api_client.utils import parse_datetime, parse_timedelta
ImportError: No module named prometheus_api_client.utils
```

Has anyone an idea what's wrong ?

Bye, Dirk

**Comment by durandom** [comment]
Did you install all dependencies via `pipenv install` ?
Maybe try to run via `pipenv python test_model.py`

**Comment by DirkFries** [comment]
Hi durandom,

thanks for the hint. My machine as some pretty old Python 2.7 installed and in the with your suggestion I found out, that Python 2.6 is required.

Thanks a lot !
