### ISSUE TITLE
SyntaxError: invalid syntax File "app.py", line 68

### ISSUE THREAD

**Issue by DirkFries** [AICoE/prometheus-anomaly-detector#97]
Hi @all,

while trying to get started with the latest version I encounterd the following error:

host:~/prometheus-anomaly-detector-master # python app.py
  File "app.py", line 68
    async def get(self):
            ^
SyntaxError: invalid syntax

Maybe this one could somehow be connected to https://github.com/AICoE/prometheus-anomaly-detector/issues/96 but I am not quite sure, so I filed 2 seperate issues

Bye, Dirk

**Comment by goern** [comment]
Heya, thanks for the issue. could you pls let us know what version of python you use?

**Comment by DirkFries** [comment]
Hi goern,

I am using Python 2.7 and I just found out, that Python 3.6 is required.
So I'm going to set up a new machine to get started with this pretty interesting project :-)

Thanks a lot!
